language: php

dist: xenial
sudo: required

cache:
  directories:
    - vendor

addons:
  apt:
    packages:
    # required for php7.3
    - libzip4

env:
  - DEPENDENCIES=""
  - DEPENDENCIES="--prefer-lowest --prefer-stable"

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3snapshot

install:
  - composer update --no-interaction --prefer-dist $DEPENDENCIES

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src tests

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - master
